name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 16.18
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.0
      - name: Grant execute permission for package.json
        run: chmod +x package.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit
